---
title: "Advanced Dashboarding"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    social: ["menu"]
    source_code: embed
    theme:
      version: 4
      bootswatch: sandstone
---

```{r setup, include=FALSE}
library(flexdashboard) # dashboard construction
library(tidyverse) # data managing
library(palmerpenguins) # Get our data
library(plotly) # Interactive Plots
library(DT) # Interactiuong tables
library(fontawesome) # Free icons
data("penguins")
```

Plots {data-navmenu="Pages"}
===========================================================================================================================

sidebar {.sidebar}
-----------------------------------------------------------------------

### Penguin Stats

The number of penguins in the dataset is `r nrow(penguins)`

Row
-----------------------------------------------------------------------

### Number of penguins

```{r}
valueBox(nrow(penguins), icon = "fa-linux")
```


Column {.tabset}
-----------------------------------------------------------------------

### Scartter plot of bill vs depth

```{r}
a <- penguins %>% ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species))+
  geom_point() + theme_light()
ggplotly(a)
```

### Boxplot of body mass vs sex

```{r}
penguins %>% ggplot(aes(x = body_mass_g, y = sex, fill = sex)) +
  geom_boxplot() + theme_light()
```

### Flipper length histogram

```{r}
penguins %>% ggplot(aes(x = flipper_length_mm, fill = species)) +
  geom_histogram() +
  facet_wrap(~species) + theme_light()
```

Data {data-navmenu="Pages"}
=============================================================================================================================

```{r}
penguins %>% datatable(extensions = "Buttons", 
                       options = list(dom = "Blfrtip",
                                      buttons = c("copy","csv", "excel", "pdf", "print")))
```


